# Generated by Django 4.2.4 on 2023-08-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_blogs_desc_alter_blogs_title_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
